const $ = s => document.querySelector(s);
let fields = [
  { type:'text', name:'your-name', label:'성함', placeholder:'성함을 입력해 주세요', required:true },
  { type:'email', name:'your-email', label:'이메일', placeholder:'example@email.com', required:true },
  { type:'select', name:'inquiry-type', label:'문의 유형', placeholder:'', options:'서비스 문의, 제휴 문의, 기타', required:true },
  { type:'textarea', name:'your-message', label:'문의 내용', placeholder:'문의 내용을 자유롭게 작성해 주세요', required:true }
];
let selected = 0;
const typeLabels = {text:'한 줄 텍스트',email:'이메일',tel:'전화번호',url:'웹사이트 URL',number:'숫자',textarea:'여러 줄 텍스트',select:'드롭다운',checkbox:'체크박스',radio:'라디오 버튼',acceptance:'동의 체크',date:'날짜'};
const shortType = {textarea:'TXT',select:'SEL',checkbox:'CHK',radio:'RAD',acceptance:'OK',email:'@',tel:'TEL',date:'DATE'};
function safe(s){return String(s||'').replace(/[\[\]]/g,'');}
function tag(f){const req=f.required?'*':''; const name=safe(f.name)||'field-name'; const ph=f.placeholder?` placeholder \"${safe(f.placeholder)}\"`:''; const phoneClass=f.type==='tel'&&f.phoneFormat?' class:cf7-phone-hyphen':''; const opts=(f.options||'').split(',').map(x=>x.trim()).filter(Boolean).join(' ');
  if(f.type==='textarea') return `[textarea${req} ${name}${ph}]`;
  if(['select','checkbox','radio'].includes(f.type)) return `[${f.type}${req} ${name} ${opts||'선택지 1 선택지 2'}]`;
  if(f.type==='acceptance') return `[acceptance ${name}] ${safe(f.label||'개인정보 처리방침에 동의합니다.')} [/acceptance]`;
  return `[${f.type}${req} ${name}${phoneClass}${ph}]`;
}
const phoneScript = `document.addEventListener('input', function (event) {\n  if (!event.target.matches('.cf7-phone-hyphen')) return;\n  const digits = event.target.value.replace(/\\D/g, '').slice(0, 11);\n  event.target.value = digits.replace(/^(02)(\\d{3,4})(\\d{4})$/, '$1-$2-$3')\n    .replace(/^(\\d{3})(\\d{3,4})(\\d{4})$/, '$1-$2-$3');\n});`;
function code(){const labels=$('#showLabels').checked;return fields.map(f=>labels&&f.type!=='acceptance'?`<label>${safe(f.label||'라벨')}\n  ${tag(f)}\n</label>`:tag(f)).join('\n\n')+'\n\n[submit "보내기"]';}
function highlight(text){return text.replace(/(\[[^\]]+\])/g,'<span class="tag">$1</span>').replace(/(placeholder)/g,'<span class="attr">$1</span>').replace(/(&quot;|\"[^\"]*\")/g,'<span class="string">$1</span>');}
function renderList(){ $('#fieldList').innerHTML=fields.map((f,i)=>`<button class="field-item ${i===selected?'selected':''}" data-index="${i}"><span class="field-icon ${f.type}">${shortType[f.type]||f.type.slice(0,3).toUpperCase()}</span><span><span class="field-name">${safe(f.label)||'제목 없음'}</span><span class="field-type">${f.type.toUpperCase()} · ${safe(f.name)||'field-name'}</span></span><span class="drag">⠿</span></button>`).join(''); document.querySelectorAll('.field-item').forEach(b=>b.onclick=()=>{selected=+b.dataset.index;render();}); }
function renderEditor(){ const f=fields[selected]; const has=!!f; $('#editorEmpty').classList.toggle('hidden',has); $('#fieldEditor').classList.toggle('hidden',!has); if(!has){$('#editorTitle').textContent='항목을 선택하세요';return} $('#editorTitle').textContent=f.label||'제목 없는 항목';$('#fieldBadge').textContent=f.type.toUpperCase();$('#inputType').value=f.type;$('#inputName').value=f.name;$('#inputLabel').value=f.label;$('#inputPlaceholder').value=f.placeholder||'';$('#inputOptions').value=f.options||'';$('#inputRequired').checked=f.required;$('#inputPhoneFormat').checked=!!f.phoneFormat;$('#optionsWrap').classList.toggle('hidden',!['select','checkbox','radio'].includes(f.type));$('#phoneFormatWrap').classList.toggle('hidden',f.type!=='tel'); }
function preview(){const out=$('#previewView');out.innerHTML=''; fields.forEach(f=>{let wrap=document.createElement('label'); if(f.type==='acceptance'){wrap.className='preview-check';wrap.innerHTML=`<input type="checkbox"> ${safe(f.label||'개인정보 처리방침에 동의합니다.')}`;out.append(wrap);return}wrap.textContent=(f.label||'라벨')+(f.required?' *':'');let el;if(f.type==='textarea')el=document.createElement('textarea');else if(f.type==='select'){el=document.createElement('select');(f.options||'선택지 1, 선택지 2').split(',').forEach(x=>{let o=document.createElement('option');o.textContent=x.trim();el.append(o)})}else if(['checkbox','radio'].includes(f.type)){wrap.className='preview-check';wrap.innerHTML=`<input type="${f.type}"> ${(f.options||'선택지').split(',')[0].trim()}`;out.append(wrap);return}else{el=document.createElement('input');el.type=f.type}el.placeholder=f.placeholder||'';el.required=f.required;if(f.type==='tel'&&f.phoneFormat)el.addEventListener('input',()=>{const d=el.value.replace(/\D/g,'').slice(0,11);el.value=d.replace(/^(02)(\d{3,4})(\d{4})$/,'$1-$2-$3').replace(/^(\d{3})(\d{3,4})(\d{4})$/,'$1-$2-$3')});wrap.append(el);out.append(wrap)});let btn=document.createElement('button');btn.className='submit-preview';btn.textContent='보내기';out.append(btn);}
function render(){renderList();renderEditor();$('#codeOutput').innerHTML=highlight(code());$('#scriptOutput').textContent=phoneScript;preview();localStorage.setItem('cf7-studio',JSON.stringify({fields,title:$('#formTitle').value,labels:$('#showLabels').checked}));}
function updateField(){if(!fields[selected])return;let f=fields[selected];f.type=$('#inputType').value;f.name=$('#inputName').value.replace(/\s+/g,'-').toLowerCase();f.label=$('#inputLabel').value;f.placeholder=$('#inputPlaceholder').value;f.options=$('#inputOptions').value;f.required=$('#inputRequired').checked;f.phoneFormat=$('#inputPhoneFormat').checked;render();}
['inputType','inputName','inputLabel','inputPlaceholder','inputOptions','inputRequired','inputPhoneFormat'].forEach(id=>$('#'+id).addEventListener('input',updateField));
$('#showLabels').onchange=render;$('#formTitle').oninput=render;
$('#generateAI').onclick=async()=>{const prompt=$('#aiPrompt').value.trim(),button=$('#generateAI'),status=$('#aiStatus');if(prompt.length<4){status.textContent='폼에 필요한 내용을 조금 더 자세히 적어 주세요.';status.classList.add('error');return}button.disabled=true;button.textContent='생성 중…';status.textContent='AI가 폼 구성과 필드명을 만들고 있습니다.';status.classList.remove('error');try{const response=await fetch('/api/generate-form',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});const data=await response.json();if(!response.ok)throw new Error(data.error||'AI 요청에 실패했습니다.');fields=data.fields;selected=0;$('#formTitle').value=data.title||'AI 생성 폼';render();status.textContent=`${fields.length}개 항목을 생성했습니다. 필요하면 각 항목을 수정하세요.`;$('#aiPrompt').value='';}catch(error){status.textContent=error.message||'AI 요청 중 오류가 발생했습니다.';status.classList.add('error');}finally{button.disabled=false;button.textContent='✦ AI로 폼 생성';}};
function add(){fields.push({type:'text',name:'new-field',label:'새 항목',placeholder:'',required:false});selected=fields.length-1;render();$('#inputLabel').focus();}
$('#addField').onclick=add;$('#addFieldWide').onclick=add;$('#deleteField').onclick=()=>{if(fields.length){fields.splice(selected,1);selected=Math.max(0,selected-1);render();}};
function copied(text){navigator.clipboard.writeText(text).then(()=>{$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800);});}function copy(){copied(code())}$('#copyCode').onclick=copy;$('#copyAll').onclick=copy;$('#copyScript').onclick=()=>copied(phoneScript);
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#codeView').classList.toggle('hidden',b.dataset.tab!=='code');$('#scriptView').classList.toggle('hidden',b.dataset.tab!=='script');$('#previewView').classList.toggle('hidden',b.dataset.tab!=='preview');});
$('#newForm').onclick=()=>{if(confirm('현재 폼을 새로 시작할까요?')){fields=[];selected=0;$('#formTitle').value='새 문의 폼';render();}};
try{let saved=JSON.parse(localStorage.getItem('cf7-studio'));if(saved?.fields){fields=saved.fields;$('#formTitle').value=saved.title||'문의하기';$('#showLabels').checked=saved.labels!==false;}}catch(e){}render();
